python_command: vllm.entrypoints.openai.api_server

llm_model_path: /content/drive/MyDrive/2024_lingo-chat-ai-server/prompt/models/PAL_orbit_v0.2.2.3

num_gpus: 1
gpu_memory_utilization: 0.9

seed: 42
max_model_len: 4096

request_port: 2496
ws_port: 8892
secure_api_key: test_api_key